version: '3'
services:
  db:
    image: postgres:9.5

  redis:
    image: redis:4-alpine

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    environment:
      - "transport.host=localhost"
      - "bootstrap.system_call_filter=false"
  sut:
    build:
      context: .
    image: "shoutit-api:test-${BUILD_TAG:-development}"
    command: dockerize -wait tcp://es:9200 -timeout 20s py.test
    environment:
      SHOUTIT_ENV: TESTING
    links:
      - db
      - es
      - redis
