version: '2'
services:
  api:
    build: .
    image: shoutit-api:development
    ports:
      - 8001:8001
    command: dockerize -wait tcp://es:9200 -timeout 20s gunicorn src.wsgi -c deploy/gunicorn.py
    links:
      - es:es
      - redis:redis

  rq:
    image: shoutit-api:development
    command: dockerize -wait tcp://es:9200 circusd deploy/circus.ini

  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  esdata:
    driver: local

# To run es and redis services only
# docker-compose run -d --service-ports --name shoutit-api-es es
# docker-compose run -d --service-ports --name shoutit-api-redis redis
