#!/bin/bash

DJANGO_WSGI_MODULE="wsgi"


BACKEND_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DJANGO_DIR="${BACKEND_DIR}/src"
ENV_DIR="$(dirname "${BACKEND_DIR}")"
ENV="$(basename "${ENV_DIR}")"


echo "Starting ${ENV} as `whoami`"

cd ${DJANGO_DIR}
exec ${ENV_DIR}/bin/gunicorn ${DJANGO_WSGI_MODULE} --config ${BACKEND_DIR}/etc/gunicorn_settings.py
