# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoutit', '0006_post_streams2_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='businesscategory',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='businesscreateapplication',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='businesscreateapplication',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='businesscreateapplication',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='businesscreateapplication',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='businesscreateapplication',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='businesscreateapplication',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='IsDisabled',
            new_name='is_disabled',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='OwnerUser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='confirmtoken',
            old_name='IsDisabled',
            new_name='is_disabled',
        ),
        migrations.RenameField(
            model_name='confirmtoken',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='Item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='OwnerBusiness',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='galleryitem',
            old_name='Item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='galleryitem',
            old_name='IsMuted',
            new_name='muted',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='ProvinceCode',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='CountryCode',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='DatePublished',
            new_name='date_published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='IsDisabled',
            new_name='is_disabled',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='IsMuted',
            new_name='muted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='OwnerUser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='predefinedcity',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='predefinedcity',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='predefinedcity',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='predefinedcity',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='IsDisabled',
            new_name='is_disabled',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sharedexperience',
            old_name='OwnerUser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shout',
            old_name='ExpiryDate',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='shout',
            old_name='ExpiryNotified',
            new_name='expiry_notified',
        ),
        migrations.RenameField(
            model_name='shoutwrap',
            old_name='Rank',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='shoutwrap',
            old_name='Shout',
            new_name='shout',
        ),
        migrations.RenameField(
            model_name='storedfile',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='storedimage',
            old_name='Item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='storedimage',
            old_name='Shout',
            new_name='shout',
        ),
        migrations.RenameField(
            model_name='stream',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='BaseDatePublished',
            new_name='base_date_published',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='IsSSS',
            new_name='is_sss',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='RenewalCount',
            new_name='renewal_count',
        ),

        migrations.RenameField(
            model_name='business',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='shout',
            old_name='Tags',
            new_name='tags',
        ),

        migrations.RemoveField(
            model_name='trade',
            name='IsShowMobile',
        ),

        migrations.RenameField(
            model_name='trade',
            old_name='Item',
            new_name='item',
        ),

        migrations.RenameField(
            model_name='trade',
            old_name='RecommendedStream',
            new_name='recommended_stream',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='RelatedStream',
            new_name='related_stream',
        ),

        migrations.AlterField(
            model_name='business',
            name='Stream',
            field=models.OneToOneField(related_name='business', null=True, blank=True, to='shoutit.Stream'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='EventType',
            field=models.IntegerField(default=0, choices=[(0, b'Follow User'), (1, b'Follow Tag'), (2, b'Shout Offer'), (3, b'Shout Request'), (4, b'Experience'), (5, b'Share Experience'), (6, b'Comment'), (7, b'Gallery item'), (8, b'Post Deal'), (9, b'Buy Deal'), (10, b'Follow Business')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='profile',
            name='Stream',
            field=models.OneToOneField(related_name='user', to='shoutit.Stream'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tag',
            name='Stream',
            field=models.OneToOneField(related_name='tag', null=True, blank=True, to='shoutit.Stream'),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='galleryitem',
            unique_together=set([('item', 'Gallery')]),
        ),
        migrations.AlterUniqueTogether(
            name='sharedexperience',
            unique_together=set([('Experience', 'user')]),
        ),
    ]
